
" Loading Plugins With Pathogen                                                           
execute pathogen#infect()

" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align" 
Plug 'junegunn/vim-easy-align'

" Comment functions so powerful—no comment necessary.
Plug 'scrooloose/nerdcommenter'

" Initialize plugin system
call plug#end()

" VIM theme:
filetype on
syntax on
colorscheme Tomorrow-Night

set colorcolumn=90
set number

" Setup map leader key - Currently set to: space
let mapleader=" "

" Reload current file - Leader key + s
map <leader>s :source ~/.vimrc<CR>

" Keep more info in memory to speed things up
set hidden
set history=100

" Indention logic
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

" Setup navigation keys
"map <D-A-RIGHT> <C-w>l
"map <D-A-LEFT> <C-w>h
"map <D-A-DOWN> <C-w><C-w>
"map <D-A-UP> <C-w>W

" TODO - FIND A Better searh functionality
"set hlsearch
" Escaping search result
"nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>

" Show Matching Parenthesis and more
set showmatch


